name: Genarate ASCII Artwork

on: push 

jobs: 
    ascii-job:
        runs-on: ubuntu-latest
        steps:
          
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List Repo Files
          run: ls -ltra

        - name: Executing Shell Script
          run: ./.github/workflows/ascii-script.sh


      